version: "3.1"

services:
  api:
    build: cmd
    ports:
      - "3000:3000"
    depends_on:
      elasticsearch:
        condition: service_healthy
  # db:
  #   build: db
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - .data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Add memory limits if needed
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  es_data:
    driver: local